'use client';
import {useEffect,useMemo,useState} from 'react';

const MLB_SORTS={hrProb:'HR estimate',hitProb:'Hit estimate',rbiProb:'RBI estimate',barrel:'Barrel / PA',hard:'Hard-hit rate',ev:'Average EV'};
const NFL_SORTS={prob:'Over probability',projection:'Projection',edge:'Model cushion'};
function mlbValue(p,key){if(key==='hrProb')return p.prob||0;if(key==='hitProb')return p.props?.hit||0;if(key==='rbiProb')return p.props?.rbi||0;if(key==='barrel')return Number(p.statcast?.barrelPA||0);if(key==='hard')return Number(p.statcast?.hardHit||0);if(key==='ev')return Number(p.statcast?.avgEV||0);return 0}
function timeLabel(iso,short=false){if(!iso)return'TBD';try{return new Intl.DateTimeFormat(undefined,short?{hour:'numeric',minute:'2-digit'}:{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(iso))}catch{return'TBD'}}
function pct(v){return v==null?'—':`${v}%`}
function signal(p){const s=[];const hard=Number(p.statcast?.hardHit||0),barrel=Number(p.statcast?.barrelPA||0),max=Number(p.statcast?.maxEV||0),pbarrel=Number(p.pitcherStatcast?.barrelPA||0);if(barrel>=7)s.push(['up',`${barrel.toFixed(1)}% barrels per PA`]);if(hard>=45)s.push(['up',`${hard.toFixed(1)}% hard-hit rate`]);if(max>=110)s.push(['up',`${max.toFixed(1)} mph max exit velocity`]);if(pbarrel>=5)s.push(['up',`Opposing starter allows ${pbarrel.toFixed(1)}% barrels/PA`]);if(barrel<4&&barrel>0)s.push(['down','Below-average barrel frequency']);if(!s.length)s.push(['flat','Limited Statcast signal available']);return s.slice(0,3)}
function nflSignal(p){const s=[];if(p.edge>=12)s.push(['up',`${p.edge.toFixed(1)} ${p.unit} above the reference line`]);if(p.hitRate>=70)s.push(['up',`Cleared this line in ${p.hitRate}% of recent games`]);if(p.usage>=20)s.push(['up',`${p.usage}% recent opportunity share`]);if(p.opponentRank&&p.opponentRank<=10)s.push(['up',`Opponent is a favorable recent matchup by this stat`]);if(p.edge<0)s.push(['down','Projection sits below the reference line']);if(!s.length)s.push(['flat','Projection is close to the reference line']);return s.slice(0,3)}

export default function Home(){
 const[sport,setSport]=useState('mlb');
 const[data,setData]=useState(null),[q,setQ]=useState(''),[sort,setSort]=useState('hrProb'),[days,setDays]=useState(1),[game,setGame]=useState('all'),[open,setOpen]=useState(null),[loading,setLoading]=useState(true),[err,setErr]=useState('');
 const[nfl,setNfl]=useState(null),[nflQ,setNflQ]=useState(''),[nflSort,setNflSort]=useState('prob'),[nflMarket,setNflMarket]=useState('all'),[nflGame,setNflGame]=useState('all'),[nflOpen,setNflOpen]=useState(null),[nflLoading,setNflLoading]=useState(false),[nflErr,setNflErr]=useState('');
 async function loadMLB(){setLoading(true);setErr('');try{const r=await fetch(`/dashboard?days=${days}`,{cache:'no-store'});const j=await r.json();setData(j);if(j.error)setErr(j.error)}catch{setErr('Could not load the MLB slate. Try again.')}finally{setLoading(false)}}
 async function loadNFL(){setNflLoading(true);setNflErr('');try{const r=await fetch('/nfl?days=7',{cache:'no-store'});const j=await r.json();setNfl(j);if(j.error)setNflErr(j.error)}catch{setNflErr('Could not load the NFL slate. Try again.')}finally{setNflLoading(false)}}
 useEffect(()=>{loadMLB()},[days]);
 useEffect(()=>{if(sport==='nfl'&&!nfl)loadNFL()},[sport]);
 const rows=useMemo(()=>{const needle=q.trim().toLowerCase();return (data?.players||[]).filter(p=>(game==='all'||String(p.gamePk)===game)&&(!needle||(`${p.name} ${p.team} ${p.opponent} ${p.probablePitcher}`).toLowerCase().includes(needle))).sort((a,b)=>mlbValue(b,sort)-mlbValue(a,sort))},[data,q,sort,game]);
 const nflRows=useMemo(()=>{const needle=nflQ.trim().toLowerCase();return (nfl?.props||[]).filter(p=>(nflGame==='all'||p.gameId===nflGame)&&(nflMarket==='all'||p.market===nflMarket)&&(!needle||(`${p.name} ${p.team} ${p.opponent} ${p.marketLabel}`).toLowerCase().includes(needle))).sort((a,b)=>(Number(b[nflSort])||0)-(Number(a[nflSort])||0))},[nfl,nflQ,nflSort,nflMarket,nflGame]);
 const games=data?.gameSummaries||[],nflGames=nfl?.games||[];
 return <main className="shell">
   <nav className="topbar"><a className="logo" href="#"><span className="frog">PF</span><span>PROPFROG</span></a><div className="sportTabs"><button className={sport==='mlb'?'active':''} onClick={()=>setSport('mlb')}>MLB</button><button className={sport==='nfl'?'active':''} onClick={()=>setSport('nfl')}>NFL <i>NEW</i></button></div><div className="navRight"><span className="liveDot"><i/> LIVE {sport.toUpperCase()} DATA</span><button className="iconBtn" onClick={sport==='mlb'?loadMLB:loadNFL} aria-label="Refresh">↻</button></div></nav>

   {sport==='mlb'?<>
   <section className="intro"><div><span className="kicker">MLB MATCHUP INTELLIGENCE</span><h1>Find the contact<br/>before the box score.</h1><p>Pregame hitter research built from Statcast contact quality, season production and probable-pitcher context.</p></div><div className="slateStamp"><span>NEXT SLATE</span><b>{data?.dates?.[0]||'Loading…'}</b><small>{data?.players?.length||0} hitters scanned · {data?.games||0} games</small></div></section>
   <section className="games"><div className="sectionHead"><div><span className="kicker">SLATE</span><h2>Upcoming games</h2></div><select value={days} onChange={e=>{setGame('all');setDays(Number(e.target.value))}}><option value="1">Next game day</option><option value="2">Next 2 game days</option><option value="3">Next 3 game days</option><option value="7">Next 7 game days</option></select></div><div className="gameRail"><button className={`gameChip ${game==='all'?'active':''}`} onClick={()=>setGame('all')}><b>ALL</b><span>Full slate</span></button>{games.map(g=><button key={g.gamePk} className={`gameChip ${game===String(g.gamePk)?'active':''}`} onClick={()=>setGame(String(g.gamePk))}><b>{g.away} <em>@</em> {g.home}</b><span>{timeLabel(g.gameTime,true)} · {g.venue||'MLB'}</span></button>)}</div></section>
   <section className="board"><div className="boardHead"><div><span className="kicker">MATCHUP BOARD</span><h2>Top hitter signals</h2></div><div className="tools"><label className="search"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Player, team or pitcher"/></label><select value={sort} onChange={e=>setSort(e.target.value)}>{Object.entries(MLB_SORTS).map(([k,v])=><option key={k} value={k}>Sort: {v}</option>)}</select></div></div>
   {loading&&!data?<div className="state"><i className="spinner"/>Building today's matchup board…</div>:rows.length?<div className="table"><div className="thead"><span>#</span><span>HITTER / MATCHUP</span><span>HR EST.</span><span>CONTACT</span><span>FAIR*</span><span/></div>{rows.map((p,i)=>{const expanded=open===`${p.gamePk}-${p.id}`;return <article className={`row ${expanded?'expanded':''}`} key={`${p.gamePk}-${p.id}`}><button className="rowMain" onClick={()=>setOpen(expanded?null:`${p.gamePk}-${p.id}`)}><span className="rank">{String(i+1).padStart(2,'0')}</span><span className="player"><b>{p.name}</b><small><strong>{p.team}</strong> vs {p.opponent} · {timeLabel(p.gameTime,true)}<br/>vs {p.probablePitcher}</small></span><span className="heroProb"><b>{pct(p.prob)}</b><i><u style={{width:`${Math.min(100,(p.prob||0)*3)}%`}}/></i></span><span className="contact"><b>{p.statcast?`${p.statcast.hardHit}% HH`:'—'}</b><small>{p.statcast?`${p.statcast.barrelPA}% Brl/PA · ${p.statcast.avgEV} EV`:'Statcast unavailable'}</small></span><span className="fair">{p.fair||'—'}</span><span className="chev">{expanded?'−':'+'}</span></button>{expanded&&<div className="drawer"><div className="why"><span className="kicker">WHY IT RATES</span><h3>Matchup signals</h3>{signal(p).map(([dir,t],x)=><p key={x}><i className={dir}>{dir==='up'?'↗':dir==='down'?'↘':'→'}</i>{t}</p>)}</div><div className="metrics"><div><span>Hit</span><b>{pct(p.props?.hit)}</b></div><div><span>RBI</span><b>{pct(p.props?.rbi)}</b></div><div><span>Walk</span><b>{pct(p.props?.walk)}</b></div><div><span>Batter K</span><b>{pct(p.props?.strikeout)}</b></div><div><span>Max EV</span><b>{p.statcast?`${p.statcast.maxEV} mph`:'—'}</b></div><div><span>Launch angle</span><b>{p.statcast?`${p.statcast.launchAngle}°`:'—'}</b></div><div><span>AVG / SLG</span><b>{p.avg} / {p.slg}</b></div><div><span>Season HR</span><b>{p.hr}</b></div></div></div>}</article>})}</div>:<div className="state">{err||'No hitters match these filters.'}</div>}</section>
   </>:<>
   <section className="intro nflIntro"><div><span className="kicker">NFL PROP INTELLIGENCE</span><h1>Turn usage into<br/>a probability.</h1><p>Player-prop research built from recent production, volume, opponent context and simple distribution models. Reference lines are research inputs — not sportsbook quotes.</p></div><div className="slateStamp"><span>NEXT NFL WINDOW</span><b>{nfl?.weekLabel||'Loading…'}</b><small>{nfl?.props?.length||0} prop estimates · {nfl?.games?.length||0} games</small></div></section>
   <section className="games"><div className="sectionHead"><div><span className="kicker">SLATE</span><h2>Upcoming NFL games</h2></div><span className="modelTag">{nfl?.model||'NFL Props v1'}</span></div><div className="gameRail"><button className={`gameChip ${nflGame==='all'?'active':''}`} onClick={()=>setNflGame('all')}><b>ALL</b><span>Full slate</span></button>{nflGames.map(g=><button key={g.gameId} className={`gameChip ${nflGame===g.gameId?'active':''}`} onClick={()=>setNflGame(g.gameId)}><b>{g.away} <em>@</em> {g.home}</b><span>{timeLabel(g.gameTime,true)} · {g.week||'NFL'}</span></button>)}</div></section>
   <section className="board"><div className="boardHead"><div><span className="kicker">PROP BOARD</span><h2>Top over probabilities</h2></div><div className="tools nflTools"><label className="search"><span>⌕</span><input value={nflQ} onChange={e=>setNflQ(e.target.value)} placeholder="Player, team or market"/></label><select value={nflMarket} onChange={e=>setNflMarket(e.target.value)}><option value="all">All markets</option><option value="passing_yards">Pass yards</option><option value="passing_tds">Pass TDs</option><option value="rushing_yards">Rush yards</option><option value="receiving_yards">Rec yards</option><option value="receptions">Receptions</option><option value="anytime_td">Anytime TD</option></select><select value={nflSort} onChange={e=>setNflSort(e.target.value)}>{Object.entries(NFL_SORTS).map(([k,v])=><option key={k} value={k}>Sort: {v}</option>)}</select></div></div>
   {nflLoading&&!nfl?<div className="state"><i className="spinner"/>Building the NFL prop board…</div>:nflRows.length?<div className="table nflTable"><div className="thead"><span>#</span><span>PLAYER / MATCHUP</span><span>OVER PROB.</span><span>PROJECTION</span><span>LINE*</span><span/></div>{nflRows.map((p,i)=>{const expanded=nflOpen===p.id;return <article className={`row ${expanded?'expanded':''}`} key={p.id}><button className="rowMain" onClick={()=>setNflOpen(expanded?null:p.id)}><span className="rank">{String(i+1).padStart(2,'0')}</span><span className="player"><b>{p.name} <em className="position">{p.position}</em></b><small><strong>{p.team}</strong> vs {p.opponent} · {timeLabel(p.gameTime,true)}<br/>{p.marketLabel}</small></span><span className="heroProb"><b>{pct(p.prob)}</b><i><u style={{width:`${Math.min(100,p.prob||0)}%`}}/></i></span><span className="contact"><b>{p.projection} {p.unit}</b><small>{p.edge>=0?'+':''}{p.edge} vs line · {p.hitRate}% recent hit rate</small></span><span className="fair">{p.line}</span><span className="chev">{expanded?'−':'+'}</span></button>{expanded&&<div className="drawer"><div className="why"><span className="kicker">WHY IT RATES</span><h3>Prop signals</h3>{nflSignal(p).map(([dir,t],x)=><p key={x}><i className={dir}>{dir==='up'?'↗':dir==='down'?'↘':'→'}</i>{t}</p>)}</div><div className="metrics"><div><span>Projection</span><b>{p.projection} {p.unit}</b></div><div><span>Reference line</span><b>{p.line}</b></div><div><span>Over probability</span><b>{pct(p.prob)}</b></div><div><span>Recent hit rate</span><b>{pct(p.hitRate)}</b></div><div><span>Recent avg</span><b>{p.recentAvg} {p.unit}</b></div><div><span>Season avg</span><b>{p.seasonAvg} {p.unit}</b></div><div><span>Usage</span><b>{pct(p.usage)}</b></div><div><span>Sample</span><b>{p.sample} games</b></div></div></div>}</article>})}</div>:<div className="state">{nflErr||'No NFL props match these filters.'}</div>}</section>
   </>}

   <footer><div><b>PROPFROG</b><span>Experimental sports research.</span></div><p>* MLB fair odds and NFL reference lines are mathematical/research context, not live sportsbook quotes. Probabilities are heuristic model estimates and are not guarantees.</p><p>{sport==='mlb'?'Sources: MLB Stats API + Baseball Savant.':'NFL data: nflverse / public NFL schedule and player-stat data.'}</p></footer>
 </main>
}
