'use client';
import {useEffect,useMemo,useState} from 'react';

const SORTS={model:'Model %',barrel:'Barrel / PA',hard:'Hard Hit %',ev:'Avg EV',hr:'Season HR'};
function value(p,key){if(key==='model')return p.prob;if(key==='barrel')return Number(p.statcast?.barrelPA||0);if(key==='hard')return Number(p.statcast?.hardHit||0);if(key==='ev')return Number(p.statcast?.avgEV||0);return p.hr||0}
function timeLabel(iso){if(!iso)return 'TBD';try{return new Intl.DateTimeFormat(undefined,{hour:'numeric',minute:'2-digit'}).format(new Date(iso))}catch{return 'TBD'}}

export default function Home(){
 const[data,setData]=useState(null),[q,setQ]=useState(''),[open,setOpen]=useState(null),[sort,setSort]=useState('model'),[min,setMin]=useState(0),[loading,setLoading]=useState(true),[err,setErr]=useState('');
 async function load(){setLoading(true);setErr('');try{const r=await fetch('/api/dashboard',{cache:'no-store'});const j=await r.json();setData(j);if(j.error)setErr(j.error)}catch{setErr('Could not load the MLB slate. Try again.')}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const rows=useMemo(()=>{const needle=q.trim().toLowerCase();return (data?.players||[]).filter(p=>p.prob>=min&&(!needle||(p.name+' '+p.team+' '+p.opponent+' '+p.probablePitcher).toLowerCase().includes(needle))).sort((a,b)=>value(b,sort)-value(a,sort))},[data,q,sort,min]);
 return <main>
  <header><div className="brand"><img className="brandLogo" src="/logo.png" alt="PropFrog logo" onError={e=>e.currentTarget.style.display='none'}/><div><span className="eyebrow">MLB · STATCAST RESEARCH</span><h1>PropFrog</h1><p>Fast pregame contact-quality and matchup research.</p></div></div><div className="live"><span/> LIVE DATA</div></header>
  <section className="hero"><div><b>{data?.games??'—'}</b><span>Games today</span></div><div><b>{data?.players?.length??'—'}</b><span>Hitters scanned</span></div><div><b>{data?.statcastAvailable?'ON':'—'}</b><span>Statcast layer</span></div></section>
  <section className="controls"><div className="search"><span>⌕</span><input aria-label="Search players" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search player, team, pitcher…"/>{q&&<button className="clear" onClick={()=>setQ('')} aria-label="Clear search">×</button>}</div><select aria-label="Sort players" value={sort} onChange={e=>setSort(e.target.value)}>{Object.entries(SORTS).map(([k,v])=><option key={k} value={k}>Sort: {v}</option>)}</select><select aria-label="Minimum estimate" value={min} onChange={e=>setMin(Number(e.target.value))}><option value="0">All estimates</option><option value="10">10%+</option><option value="15">15%+</option><option value="20">20%+</option></select><button className="refresh" onClick={load} disabled={loading}>{loading?'Loading…':'Refresh'}</button></section>
  {data&&<div className="meta"><span>{rows.length} results</span><span>{data.model}</span><span>Updated {data.generatedAt?timeLabel(data.generatedAt):'recently'}</span></div>}
  {loading&&!data?<div className="empty"><div className="spinner"/>Loading today's MLB slate + Statcast…</div>:rows.length?<section className="grid">{rows.map((p,i)=><article key={`${p.gamePk}-${p.id}`} className="card"><button className="cardButton" onClick={()=>setOpen(open===p.id?null:p.id)} aria-expanded={open===p.id}><div className="rank">#{i+1}</div><div className="who"><h2>{p.name}</h2><p><b>{p.team}</b> vs {p.opponent} · {timeLabel(p.gameTime)}</p><p>Opp. SP: {p.probablePitcher}</p></div><div className="prob"><strong>{p.prob}%</strong><span>HR estimate</span></div><div className="meter"><i style={{width:`${Math.min(100,p.prob*2.85)}%`}}/></div><div className="stats"><div><span>Barrel/PA</span><b>{p.statcast?`${p.statcast.barrelPA}%`:'—'}</b></div><div><span>Hard Hit</span><b>{p.statcast?`${p.statcast.hardHit}%`:'—'}</b></div><div><span>Avg EV</span><b>{p.statcast?`${p.statcast.avgEV} mph`:'—'}</b></div><div><span>Max EV</span><b>{p.statcast?`${p.statcast.maxEV} mph`:'—'}</b></div><div><span>Fair*</span><b>{p.fair}</b></div></div></button>{open===p.id&&<div className="detail"><div className="detailHead"><h3>Research profile</h3><span>Season-to-date</span></div><div className="detailgrid"><div><span>Launch angle</span><b>{p.statcast?`${p.statcast.launchAngle}°`:'—'}</b></div><div><span>Barrel / BBE</span><b>{p.statcast?`${p.statcast.barrelBBE}%`:'—'}</b></div><div><span>Batted balls</span><b>{p.statcast?.bbe||'—'}</b></div><div><span>Season HR</span><b>{p.hr}</b></div><div><span>AVG / SLG</span><b>{p.avg} / {p.slg}</b></div><div><span>SP Barrel/PA allowed</span><b>{p.pitcherStatcast?`${p.pitcherStatcast.barrelPA}%`:'TBD'}</b></div></div></div>}</article>)}</section>:<div className="empty">{err||'No players match these filters.'}</div>}
  <footer><p>*{data?.note||'Experimental research estimate.'} Fair odds are a mathematical conversion of the displayed estimate, not a sportsbook quote.</p><p>Sources: MLB Stats API and Baseball Savant. Use as research context, not as a guarantee of outcomes.</p></footer>
 </main>
}
