import {NextResponse} from 'next/server';
const MLB='https://statsapi.mlb.com/api/v1',SAVANT='https://baseballsavant.mlb.com';
async function json(url){const r=await fetch(url,{next:{revalidate:900}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
async function text(url){const r=await fetch(url,{next:{revalidate:3600}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.text()}
function csvLine(line){let a=[],s='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){s+='"';i++}else q=!q}else if(c===','&&!q){a.push(s);s=''}else s+=c}a.push(s);return a}
function csv(raw){const lines=raw.trim().split(/\r?\n/);if(lines.length<2)return[];const h=csvLine(lines[0]);return lines.slice(1).map(l=>{const v=csvLine(l),o={};h.forEach((k,i)=>o[k.trim()]=v[i]);return o})}
function n(v,d=0){const x=Number(v);return Number.isFinite(x)?x:d}
function fair(p){if(p<=0)return null;return p>=50?Math.round(-100*p/(100-p)):Math.round(100*(100-p)/p)}
function fmtOdds(x){return x==null?'—':x>0?`+${x}`:`${x}`}
function isoDate(d){return d.toISOString().slice(0,10)}
function addDays(d,days){const x=new Date(d);x.setUTCDate(x.getUTCDate()+days);return x}
async function statcast(type,year){try{const rows=csv(await text(`${SAVANT}/leaderboard/statcast?type=${type}&year=${year}&min=1&csv=true`)),m=new Map();for(const r of rows){const id=String(r.player_id||r.batter||r.pitcher||'');if(id)m.set(id,r)}return m}catch{return new Map()}}
function clamp(x,a,b){return Math.max(a,Math.min(b,x))}
function propModels(h,bs,ps){const pa=n(h.plateAppearances),ab=n(h.atBats),hits=n(h.hits),rbi=n(h.rbi),bb=n(h.baseOnBalls),so=n(h.strikeOuts),avg=ab?hits/ab:n(h.avg),bbpa=pa?bb/pa:.08,kpa=pa?so/pa:.22,rbiPa=pa?rbi/pa:.12,hard=n(bs?.ev95percent,38)/100,brl=n(bs?.brl_pa,3)/100,pHard=n(ps?.ev95percent,38)/100,pBrl=n(ps?.brl_pa,3)/100;const hit=clamp((avg*.72+hard*.13+(1-kpa)*.06+.04)*100,8,62),walk=clamp((bbpa*.78+.018)*100,2,24),strikeout=clamp((kpa*.82+.035)*100,7,45),rbiProb=clamp((rbiPa*.58+brl*.20+hard*.045+pBrl*.06+.025)*100,4,42);return{hit:Number(hit.toFixed(1)),rbi:Number(rbiProb.toFixed(1)),walk:Number(walk.toFixed(1)),strikeout:Number(strikeout.toFixed(1))}}
function model(h,bs,ps){const pa=n(h.plateAppearances),hr=n(h.homeRuns),hrpa=pa?hr/pa:.03,brl=n(bs?.brl_pa)/100,hard=n(bs?.ev95percent)/100,ev=n(bs?.avg_hit_speed,88),maxev=n(bs?.max_hit_speed,105),la=n(bs?.avg_hit_angle,12),pbrl=n(ps?.brl_pa,3)/100,phard=n(ps?.ev95percent,38)/100,pev=n(ps?.avg_hit_speed,88),contact=brl*.46+hard*.08+Math.max(0,ev-86)*.003+Math.max(0,maxev-105)*.0015,pitcher=pbrl*.18+phard*.025+Math.max(0,pev-87)*.002,angle=la>=10&&la<=30?.012:0,p=Math.max(2,Math.min(35,(.018+hrpa*.38+contact+pitcher+angle)*100));return Number(p.toFixed(1))}
async function hitterCard(h,team,opp,pitcher,g,batSC,pitSC,year){try{const st=await json(`${MLB}/people/${h.person.id}/stats?stats=season&group=hitting&season=${year}`),s=st.stats?.[0]?.splits?.[0]?.stat||{},bs=batSC.get(String(h.person.id)),ps=pitcher?pitSC.get(String(pitcher.id)):null,prob=model(s,bs,ps),props=propModels(s,bs,ps);return{id:h.person.id,name:h.person.fullName,team:team.abbreviation||team.name,opponent:opp?.abbreviation||opp?.name||'',gamePk:g.gamePk,gameTime:g.gameDate,gameDate:String(g.officialDate||g.gameDate||'').slice(0,10),venue:g.venue?.name||'',probablePitcher:pitcher?.fullName||'TBD',hr:n(s.homeRuns),hits:n(s.hits),rbi:n(s.rbi),walks:n(s.baseOnBalls),strikeouts:n(s.strikeOuts),pa:n(s.plateAppearances),avg:s.avg||'—',slg:s.sluggingPercentage||'—',prob,props,fair:fmtOdds(fair(prob)),statcast:bs?{avgEV:n(bs.avg_hit_speed).toFixed(1),maxEV:n(bs.max_hit_speed).toFixed(1),launchAngle:n(bs.avg_hit_angle).toFixed(1),hardHit:n(bs.ev95percent).toFixed(1),barrelBBE:n(bs.brl_percent).toFixed(1),barrelPA:n(bs.brl_pa).toFixed(1),bbe:n(bs.attempts)}:null,pitcherStatcast:ps?{avgEV:n(ps.avg_hit_speed).toFixed(1),hardHit:n(ps.ev95percent).toFixed(1),barrelPA:n(ps.brl_pa).toFixed(1)}:null}}catch{return null}}
export async function GET(req){try{
 const url=new URL(req.url),days=Math.max(1,Math.min(7,Number(url.searchParams.get('days')||3))),now=new Date(),start=isoDate(now),end=isoDate(addDays(now,days+14));
 const sched=await json(`${MLB}/schedule?sportId=1&startDate=${start}&endDate=${end}&hydrate=probablePitcher,team,venue`);
 const all=(sched.dates||[]).flatMap(d=>(d.games||[]).map(g=>({...g,officialDate:g.officialDate||d.date}))).filter(g=>new Date(g.gameDate).getTime()>now.getTime()-3*60*60*1000);
 const dates=[...new Set(all.map(g=>g.officialDate))].sort().slice(0,days),games=all.filter(g=>dates.includes(g.officialDate)).slice(0,45),year=Number((dates[0]||start).slice(0,4));
 const [batSC,pitSC]=await Promise.all([statcast('batter',year),statcast('pitcher',year)]),teamJobs=[];
 for(const g of games)for(const side of ['away','home'])teamJobs.push((async()=>{const team=g.teams?.[side]?.team;if(!team)return[];const oppSide=side==='home'?'away':'home',opp=g.teams?.[oppSide]?.team,pitcher=g.teams?.[oppSide]?.probablePitcher;try{const roster=await json(`${MLB}/teams/${team.id}/roster?rosterType=active`),hitters=(roster.roster||[]).filter(x=>x.position?.type!=='Pitcher').slice(0,10);return (await Promise.all(hitters.map(h=>hitterCard(h,team,opp,pitcher,g,batSC,pitSC,year)))).filter(Boolean)}catch{return[]}})());
 const cards=(await Promise.all(teamJobs)).flat().sort((a,b)=>new Date(a.gameTime)-new Date(b.gameTime)||b.prob-a.prob);
 const gameSummaries=games.map(g=>({gamePk:g.gamePk,gameTime:g.gameDate,gameDate:g.officialDate,away:g.teams?.away?.team?.abbreviation||g.teams?.away?.team?.name,home:g.teams?.home?.team?.abbreviation||g.teams?.home?.team?.name,awayPitcher:g.teams?.away?.probablePitcher?.fullName||'TBD',homePitcher:g.teams?.home?.probablePitcher?.fullName||'TBD',venue:g.venue?.name||''}));
 return NextResponse.json({date:start,dates,generatedAt:new Date().toISOString(),games:games.length,gameSummaries,players:cards.slice(0,220),statcastAvailable:batSC.size>0,model:'Statcast Research v2',note:'Upcoming-game research estimates for HR, hit, RBI, walk and batter strikeout outcomes using season production plus available Statcast contact quality and probable-pitcher context. These are experimental heuristic probabilities, not historically calibrated betting models. Probable pitchers and lineups can change.'});
 }catch{return NextResponse.json({date:new Date().toISOString().slice(0,10),dates:[],generatedAt:new Date().toISOString(),games:0,gameSummaries:[],players:[],error:'Live MLB data is temporarily unavailable.'},{status:200})}}
